// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing Henaket icons.
///
/// This font was generated by FlutterIcon.com.
class HenaketIcons {
  /// No need for constructor. All properties are static.
  HenaketIcons._();

  /// Henaket icons family name.
  static const _kFontFam = 'HenaketIcons';

  /// Henaket icons package name.
  static const String? _kFontPkg = 'henaket_icons';

  /// Icon data for 'add_document' glyph.
  static const IconData add_document =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'add_person' glyph.
  static const IconData add_person =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'add_image' glyph.
  static const IconData add_image =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'add_to_list' glyph.
  static const IconData add_to_list =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'analysis' glyph.
  static const IconData analysis =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_down' glyph.
  static const IconData arrow_down =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_right' glyph.
  static const IconData arrow_right =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'attach' glyph.
  static const IconData attach =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_up' glyph.
  static const IconData arrow_up =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'availability' glyph.
  static const IconData availability =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_left' glyph.
  static const IconData arrow_left =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'back' glyph.
  static const IconData back =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'background_color' glyph.
  static const IconData background_color =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bold' glyph.
  static const IconData bold =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bookmark' glyph.
  static const IconData bookmark =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bookmarks' glyph.
  static const IconData bookmarks =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bullet_list' glyph.
  static const IconData bullet_list =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar_1' glyph.
  static const IconData calendar_1 =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar' glyph.
  static const IconData calendar =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'camera' glyph.
  static const IconData camera =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'car' glyph.
  static const IconData car =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cart' glyph.
  static const IconData cart =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chat' glyph.
  static const IconData chat =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chevron_up' glyph.
  static const IconData chevron_up =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chevron_down' glyph.
  static const IconData chevron_down =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clear_text_formatting' glyph.
  static const IconData clear_text_formatting =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'close' glyph.
  static const IconData close =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'centered_text' glyph.
  static const IconData centered_text =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'close_full_screen' glyph.
  static const IconData close_full_screen =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'contact_information_1' glyph.
  static const IconData contact_information_1 =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'checklist' glyph.
  static const IconData checklist =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'contact_information' glyph.
  static const IconData contact_information =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'copy' glyph.
  static const IconData copy =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'corona' glyph.
  static const IconData corona =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'corporation' glyph.
  static const IconData corporation =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'craft' glyph.
  static const IconData craft =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'create_folder' glyph.
  static const IconData create_folder =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'credit_card' glyph.
  static const IconData credit_card =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'data' glyph.
  static const IconData data =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'desktop' glyph.
  static const IconData desktop =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'delete' glyph.
  static const IconData delete =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'detail_closed' glyph.
  static const IconData detail_closed =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'detail_open' glyph.
  static const IconData detail_open =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'document' glyph.
  static const IconData document =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'download' glyph.
  static const IconData download =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'download_completed' glyph.
  static const IconData download_completed =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'edit' glyph.
  static const IconData edit =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'email' glyph.
  static const IconData email =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'excel' glyph.
  static const IconData excel =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'external_link' glyph.
  static const IconData external_link =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'feedback' glyph.
  static const IconData feedback =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'error' glyph.
  static const IconData error =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'fold_dropdown' glyph.
  static const IconData fold_dropdown =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'flag_filled' glyph.
  static const IconData flag_filled =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'flag_stroke' glyph.
  static const IconData flag_stroke =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'forum' glyph.
  static const IconData forum =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder' glyph.
  static const IconData folder =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'full_screen' glyph.
  static const IconData full_screen =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'forward' glyph.
  static const IconData forward =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'done' glyph.
  static const IconData done =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'group' glyph.
  static const IconData group =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'forward_1' glyph.
  static const IconData forward_1 =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'headset' glyph.
  static const IconData headset =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'help' glyph.
  static const IconData help =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'hide' glyph.
  static const IconData hide =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'home' glyph.
  static const IconData home =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image' glyph.
  static const IconData image =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'indent_left' glyph.
  static const IconData indent_left =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'indent_right' glyph.
  static const IconData indent_right =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'italic' glyph.
  static const IconData italic =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'information' glyph.
  static const IconData information =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list_completed' glyph.
  static const IconData list_completed =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'language' glyph.
  static const IconData language =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'link' glyph.
  static const IconData link =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'left_aligned' glyph.
  static const IconData left_aligned =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'laptop' glyph.
  static const IconData laptop =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_open' glyph.
  static const IconData lock_open =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_closed' glyph.
  static const IconData lock_closed =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'map' glyph.
  static const IconData map =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mobile' glyph.
  static const IconData mobile =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minus' glyph.
  static const IconData minus =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'money' glyph.
  static const IconData money =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list' glyph.
  static const IconData list =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'location' glyph.
  static const IconData location =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'menu' glyph.
  static const IconData menu =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'menu_swap' glyph.
  static const IconData menu_swap =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'more_menu_items_horizontal' glyph.
  static const IconData more_menu_items_horizontal =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mouse' glyph.
  static const IconData mouse =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'move' glyph.
  static const IconData move =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'no_sorted' glyph.
  static const IconData no_sorted =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'notification' glyph.
  static const IconData notification =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'numbered_list' glyph.
  static const IconData numbered_list =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'open_folder' glyph.
  static const IconData open_folder =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'overflow_menu_vertical' glyph.
  static const IconData overflow_menu_vertical =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'overview' glyph.
  static const IconData overview =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pagination_first' glyph.
  static const IconData pagination_first =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pagination_last' glyph.
  static const IconData pagination_last =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pagination_next' glyph.
  static const IconData pagination_next =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pagination_previous' glyph.
  static const IconData pagination_previous =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'palette' glyph.
  static const IconData palette =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'parameter' glyph.
  static const IconData parameter =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pdf' glyph.
  static const IconData pdf =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pending' glyph.
  static const IconData pending =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'person' glyph.
  static const IconData person =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus' glyph.
  static const IconData plus =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'print' glyph.
  static const IconData print =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'proxy_profile' glyph.
  static const IconData proxy_profile =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'refresh' glyph.
  static const IconData refresh =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'remove_person' glyph.
  static const IconData remove_person =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'reply' glyph.
  static const IconData reply =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'right_aligned' glyph.
  static const IconData right_aligned =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'save' glyph.
  static const IconData save =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'science' glyph.
  static const IconData science =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'search' glyph.
  static const IconData search =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'send' glyph.
  static const IconData send =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'settings' glyph.
  static const IconData settings =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'share' glyph.
  static const IconData share =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'show_in_list_form_and_window' glyph.
  static const IconData show_in_list_form_and_window =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'show_in_list_form' glyph.
  static const IconData show_in_list_form =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'show' glyph.
  static const IconData show =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sort_alphabetically' glyph.
  static const IconData sort_alphabetically =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sorting_default' glyph.
  static const IconData sorting_default =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sorting_descending' glyph.
  static const IconData sorting_descending =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sorting' glyph.
  static const IconData sorting =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star_filled' glyph.
  static const IconData star_filled =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star_stroke' glyph.
  static const IconData star_stroke =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'statement' glyph.
  static const IconData statement =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'straight_margins' glyph.
  static const IconData straight_margins =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'student_1' glyph.
  static const IconData student_1 =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'student' glyph.
  static const IconData student =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'submenu_left' glyph.
  static const IconData submenu_left =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'submenu_right' glyph.
  static const IconData submenu_right =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'success' glyph.
  static const IconData success =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'support_1' glyph.
  static const IconData support_1 =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'support' glyph.
  static const IconData support =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'synchronize' glyph.
  static const IconData synchronize =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'table_ascending' glyph.
  static const IconData table_ascending =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'table_descending' glyph.
  static const IconData table_descending =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'task' glyph.
  static const IconData task =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'text_color' glyph.
  static const IconData text_color =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'text_format' glyph.
  static const IconData text_format =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'text_size' glyph.
  static const IconData text_size =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'time' glyph.
  static const IconData time =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'tractor' glyph.
  static const IconData tractor =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'truck' glyph.
  static const IconData truck =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'underline' glyph.
  static const IconData underline =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'upload' glyph.
  static const IconData upload =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_profile' glyph.
  static const IconData user_profile =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'users' glyph.
  static const IconData users =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'videocamera' glyph.
  static const IconData videocamera =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'warning' glyph.
  static const IconData warning =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'word' glyph.
  static const IconData word =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'worker' glyph.
  static const IconData worker =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_in' glyph.
  static const IconData zoom_in =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_out' glyph.
  static const IconData zoom_out =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'table_none' glyph.
  static const IconData table_none =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
